merge request
lgou2w/l2scripts pull request #2
Opened 2019-06-17 16:40 UTC by ShaojieHe

tested in the virtual machine and ready to be merged

2019-06-17 23:24 UTC, lgou2w commented
在这个仓库用中文就可以啦 😆

2019-06-17 23:25 UTC, lgou2w commented on centos7-standard-init/run.sh
> +echo "adding dockers usergroup && join usergroup"
这里为什么要添加用户组鸭，不明白

2019-06-17 23:26 UTC, lgou2w requested changes
需要确认

2019-06-18 03:45 UTC, ShaojieHe commented
这个主要是因为安全原因 用sudo开docker可能会有隐藏的0days漏洞
然后同时也不用在每次开docker前都加sudo了

2019-06-18 03:46 UTC, lgou2w approved these changes
passed

2019-06-18 03:47 UTC, merged